# Site settings
title: Purvesh Makode
description: My Personal Site
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Purvesh Makode
user_description: I'm a final-year Information Technology student at Government College Of Engineering Aurangabad, India. I love to build things, always love to learn new things about new technologies.<br/>I tend to waste my free time reading news, watching TV shows, playing sports, listening to EDM music, or spend some time coding my small side-projects.
user_title: IT Junior Undergraduate
email: makodepurvesh@gmail.com
twitter_username: purveshmakode24
github_username:  purveshmakode24
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
